[project]
name = "{{cookiecutter.project_slug}}"
version = "0.1"
description = ""
readme = "README.md"
authors = []
license = "MIT"
dependencies = [
    "apis-core-rdf=0.29.0",
    "apis-acdhch-default-settings=1.4.0",
]
